apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-server
  namespace: anz-name-space
  labels:
    app: registry-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-server
  template:
    metadata:
      labels:
        app: registry-server
    spec:
      containers:
        - name: registry-server
          image: anil16/registry
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761