apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: anz-name-space
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: registry-server
